### ISSUE TITLE
Add JWT authentication

### ISSUE THREAD

**Issue by pedrocelso** [pedrocelso/go-rest-service#9]
Add middleware that will add the user data on an `Context`. This will leverage the `Task` creation for `Users`.

Acceptance Criteria:
1. The `JWT` token payload should look like:
`{
  "name": "Pedro Costa",
  "email": "pedrocelsonunes@gmail.com"
}`
2. The secret should be added to the environment.
3. The middleware should be unit tested.

It goes without saying that the JWT token need to be parsed.

**Comment by ananichev** [comment]
@pedrocelso I'll take it!

**Comment by pedrocelso** [comment]
@ananichev cool, let me know if you have any questions regarding app engine setup, or the project itself.

**Comment by pedrocelso** [comment]
#10
